/**
 * Base de Dados Oficial e Estruturada do TRT-8 (Belém)
 * Contém o mapeamento detalhado dos prédios:
 * 1. Fórum Trabalhista de Belém (Edifício Des. José Maria Quadros de Alencastro - Tv. Dom Pedro I, 698)
 * 2. Edifício-Sede do TRT-8 (Tv. Dom Pedro I, 746)
 */

const DADOS_LOCAIS_INICIAIS = [
  {
    id: "bloco1-capela-ecumenica",
    nome: "Capela Ecumênica",
    sigla: "Capela",
    categoria: "bloco1",
    predio: "Bloco 1",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "Térreo",
    numeroAndar: 0,
    referencia: "Bloco 1, térreo, área de apoio espiritual da unidade.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["capela", "ecumenica", "bloco 1", "terreo", "espiritual"]
  },
  {
    id: "bloco1-codse",
    nome: "CODSE - Coordenadoria de Segurança Institucional",
    sigla: "CODSE",
    categoria: "bloco1",
    predio: "Bloco 1",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "Térreo",
    numeroAndar: 0,
    referencia: "Bloco 1, térreo, na área de segurança institucional do tribunal.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["codse", "seguranca", "institucional", "bloco 1", "terreo"]
  },
  {
    id: "bloco1-banheiros",
    nome: "Banheiros",
    sigla: "Banheiros",
    categoria: "bloco1",
    predio: "Bloco 1",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "Térreo",
    numeroAndar: 0,
    referencia: "Bloco 1, térreo, na circulação principal do prédio.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["banheiro", "wc", "bloco 1", "terreo", "sanitario"]
  },
  {
    id: "bloco1-amatra8",
    nome: "AMATRA8 - Associação dos Magistrados da Justiça do Trabalho da 8ª Região",
    sigla: "AMATRA8",
    categoria: "bloco1",
    predio: "Bloco 1",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "1º Andar",
    numeroAndar: 1,
    referencia: "Bloco 1, 1º andar, área de apoio institucional e convivência dos magistrados.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["amatra8", "magistrados", "justica do trabalho", "bloco 1", "1 andar"]
  },
  {
    id: "bloco1-ccs",
    nome: "CCS - Centro de Controle de Segurança",
    sigla: "CCS",
    categoria: "bloco1",
    predio: "Bloco 1",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "1º Andar",
    numeroAndar: 1,
    referencia: "Bloco 1, 1º andar, setor responsável pelo monitoramento e controle de segurança.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["ccs", "controle de seguranca", "seguranca", "bloco 1", "1 andar"]
  },
  {
    id: "bloco1-secom",
    nome: "SECOM - Secretaria de Comunicação",
    sigla: "SECOM",
    categoria: "bloco1",
    predio: "Bloco 1",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "3º Andar",
    numeroAndar: 3,
    referencia: "Bloco 1, 3º andar, área de comunicação institucional do tribunal.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["secom", "comunicacao", "bloco 1", "3 andar"]
  },
  {
    id: "bloco1-sescoc",
    nome: "SESOC - Seção de Apoio aos Programas Sociais",
    sigla: "SESOC",
    categoria: "bloco1",
    predio: "Bloco 1",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "3º Andar",
    numeroAndar: 3,
    referencia: "Bloco 1, 3º andar, setor de apoio a programas sociais e ações externas.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["sesoc", "sescoc", "programas sociais", "apoio social", "bloco 1", "3 andar"]
  },
  {
    id: "bloco2-ajutra8",
    nome: "AAJUTRA8 - Associação dos Aposentados da Justiça do Trabalho da 8ª Região",
    sigla: "AAJUTRA8",
    categoria: "bloco2",
    predio: "Bloco 2",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "Térreo",
    numeroAndar: 0,
    referencia: "Bloco 2, térreo, área de apoio à associação de aposentados.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["aajutra8", "ajutra8", "aposentados", "associacao", "bloco 2", "terreo"]
  },
  {
    id: "bloco2-coinf",
    nome: "COINF - Coordenadoria de Informações Funcionais",
    sigla: "COINF",
    categoria: "bloco2",
    predio: "Bloco 2",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "Térreo",
    numeroAndar: 0,
    referencia: "Bloco 2, térreo, setor de informações funcionais e gestão de dados de pessoal.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["coinf", "informacoes funcionais", "pessoal", "bloco 2", "terreo"]
  },
  {
    id: "bloco2-dimag",
    nome: "DIMAG - Divisão de Programação de Movimentação e Pessoas",
    sigla: "DIMAG",
    categoria: "bloco2",
    predio: "Bloco 2",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "Térreo",
    numeroAndar: 0,
    referencia: "Bloco 2, térreo, setor responsável pela movimentação funcional e logística de pessoal.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["dimag", "movimentacao", "pessoas", "bloco 2", "terreo"]
  },
  {
    id: "bloco2-sepre",
    nome: "SEPRE - Seção de Programas de Estágio",
    sigla: "SEPRE",
    categoria: "bloco2",
    predio: "Bloco 2",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "Térreo",
    numeroAndar: 0,
    referencia: "Bloco 2, térreo, setor de estágio e apoio à formação profissional.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["sepre", "estagio", "estagiarios", "bloco 2", "terreo"]
  },
  {
    id: "bloco2-nudid",
    nome: "NUDID - Núcleo de Direitos e Deveres (COLEP)",
    sigla: "NUDID",
    categoria: "bloco2",
    predio: "Bloco 2",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "Térreo",
    numeroAndar: 0,
    referencia: "Bloco 2, térreo, núcleo de apoio à legislação e direitos e deveres dos servidores.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["nudid", "direitos", "deveres", "colep", "bloco 2", "terreo"]
  },
  {
    id: "bloco2-segep",
    nome: "SEGEP - Secretaria de Gestão de Pessoas",
    sigla: "SEGEP",
    categoria: "bloco2",
    predio: "Bloco 2",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "1º Andar",
    numeroAndar: 1,
    referencia: "Bloco 2, 1º andar, setor de gestão de pessoas e administração funcional.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["segep", "gestao de pessoas", "pessoal", "bloco 2", "1 andar"]
  },
  {
    id: "bloco2-codep",
    nome: "CODEP - Coordenadoria de Desenvolvimento de Pessoas",
    sigla: "CODEP",
    categoria: "bloco2",
    predio: "Bloco 2",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "1º Andar",
    numeroAndar: 1,
    referencia: "Bloco 2, 1º andar, área de desenvolvimento de pessoal e capacitação.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["codep", "desenvolvimento", "pessoas", "capacitação", "bloco 2", "1 andar"]
  },
  {
    id: "bloco2-colep",
    nome: "COLEP - Coordenadoria de Legislação e Normatização",
    sigla: "COLEP",
    categoria: "bloco2",
    predio: "Bloco 2",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "1º Andar",
    numeroAndar: 1,
    referencia: "Bloco 2, 1º andar, área de legislação, normas e suporte jurídico-administrativo.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["colep", "legislacao", "normatizacao", "juridico", "bloco 2", "1 andar"]
  },
  {
    id: "bloco2-seabe",
    nome: "SEABE - Seção de Aposentadorias e Benefícios Previdenciários",
    sigla: "SEABE",
    categoria: "bloco2",
    predio: "Bloco 2",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "1º Andar",
    numeroAndar: 1,
    referencia: "Bloco 2, 1º andar, setor de aposentadorias e benefícios previdenciários.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["seabe", "aposentadoria", "beneficios previdenciarios", "bloco 2", "1 andar"]
  },
  {
    id: "bloco2-dimag-atendimento-magistrados",
    nome: "DIMAG - Divisão de Atendimento a Magistrados (COINF)",
    sigla: "DIMAG",
    categoria: "bloco2",
    predio: "Bloco 2",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "1º Andar",
    numeroAndar: 1,
    referencia: "Bloco 2, 1º andar, atendimento específico a magistrados e apoio funcional.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["dimag", "magistrados", "atendimento", "coinf", "bloco 2", "1 andar"]
  },
  {
    id: "bloco2-sesau",
    nome: "SESAU - Secretaria de Saúde",
    sigla: "SESAU",
    categoria: "bloco2",
    predio: "Bloco 2",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "2º Andar",
    numeroAndar: 2,
    referencia: "Bloco 2, 2º andar, secretaria de saúde institucional.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["sesau", "saude", "bloco 2", "2 andar"]
  },
  {
    id: "bloco2-codsa",
    nome: "CODSA - Coordenadoria de Saúde",
    sigla: "CODSA",
    categoria: "bloco2",
    predio: "Bloco 2",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "2º Andar",
    numeroAndar: 2,
    referencia: "Bloco 2, 2º andar, área de saúde ocupacional e coordenadoria de saúde.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["codsa", "saude", "ocupacional", "bloco 2", "2 andar"]
  },
  {
    id: "bloco2-sepsi",
    nome: "SEPSI - Seção de Suporte Psicológico da CODSA",
    sigla: "SEPSI",
    categoria: "bloco2",
    predio: "Bloco 2",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "2º Andar",
    numeroAndar: 2,
    referencia: "Bloco 2, 2º andar, suporte psicológico e acolhimento dos servidores.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["sepsi", "psicologico", "saude mental", "codsa", "bloco 2", "2 andar"]
  },
  {
    id: "bloco2-copep",
    nome: "COPEP - Coordenadoria de Gestão da Informação",
    sigla: "COPEP",
    categoria: "bloco2",
    predio: "Bloco 2",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "2º Andar",
    numeroAndar: 2,
    referencia: "Bloco 2, 2º andar, área de gestão da informação e dados institucionais.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["copep", "gestao da informacao", "dados", "bloco 2", "2 andar"]
  },
  {
    id: "bloco2-pas",
    nome: "PAS - Plano de Assistência à Saúde",
    sigla: "PAS",
    categoria: "bloco2",
    predio: "Bloco 2",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "2º Andar",
    numeroAndar: 2,
    referencia: "Bloco 2, 2º andar, setor de assistência e gestão do plano de saúde.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["pas", "assistencia a saude", "plano de saude", "bloco 2", "2 andar"]
  },
  {
    id: "bloco2-2andar-copas",
    nome: "COPAS - Coordenadoria de Planejamento e Administração de Serviços",
    sigla: "COPAS",
    categoria: "bloco2",
    predio: "Bloco 2",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "2º Andar",
    numeroAndar: 2,
    referencia: "Bloco 2, 2º andar, COPAS.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["copas", "bloco 2", "2 andar"]
  },
  {
    id: "bloco2-dinfa",
    nome: "DINFA - Divisão de Apoio à Combate ao Trabalho Infantil e de Estímulo à Aprendizagem",
    sigla: "DINFA",
    categoria: "bloco2",
    predio: "Bloco 2",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "3º Andar",
    numeroAndar: 3,
    referencia: "Bloco 2, 3º andar, equipe de apoio a políticas de combate ao trabalho infantil e estímulo à aprendizagem.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["dinfa", "trabalho infantil", "aprendizagem", "bloco 2", "3 andar"]
  },
  {
    id: "bloco3-ecaiss",
    nome: "ECAISS - Escola de Capacitação de Servidores do TRT-8",
    sigla: "ECAISS",
    categoria: "bloco3",
    predio: "Bloco 3",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "Térreo",
    numeroAndar: 0,
    referencia: "Bloco 3, térreo, espaço de capacitação e treinamento dos servidores do tribunal.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["ecaiss", "escola de capacitacao", "treinamento", "bloco 3", "terreo"]
  },
  {
    id: "bloco4-deposito-reciclaveis",
    nome: "Depósito de Resíduos Recicláveis",
    sigla: "Recicláveis",
    categoria: "bloco4",
    predio: "Bloco 4",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "Térreo",
    numeroAndar: 0,
    referencia: "Bloco 4, térreo, área de armazenamento e segregação de resíduos recicláveis.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["residuos reciclaveis", "reciclagem", "bloco 4", "terreo"]
  },
  {
    id: "bloco4-bicicletario",
    nome: "Bicicletário",
    sigla: "Bicicletário",
    categoria: "bloco4",
    predio: "Bloco 4",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "Térreo",
    numeroAndar: 0,
    referencia: "Bloco 4, térreo, espaço para guarda de bicicletas dos servidores e visitantes.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["bicicletario", "bike", "bloco 4", "terreo"]
  },
  {
    id: "bloco4-cocin",
    nome: "COCIN - Coordenadoria de Controle e Integridade",
    sigla: "COCIN",
    categoria: "bloco4",
    predio: "Bloco 4",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "1º Andar",
    numeroAndar: 1,
    referencia: "Bloco 4, 1º andar, coordenação de controle e integridade institucional.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["cocin", "controle", "integridade", "bloco 4", "1 andar"]
  },
  {
    id: "bloco4-digea",
    nome: "DIGEA - Divisão de Conformidade de Gestão e Administração",
    sigla: "DIGEA",
    categoria: "bloco4",
    predio: "Bloco 4",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "1º Andar",
    numeroAndar: 1,
    referencia: "Bloco 4, 1º andar, área de conformidade de gestão e administração.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["digea", "conformidade", "gestao", "administracao", "bloco 4", "1 andar"]
  },
  {
    id: "bloco4-nudac",
    nome: "NUCAD - Núcleo de Controladoria Administrativa e Integridade",
    sigla: "NUCAD",
    categoria: "bloco4",
    predio: "Bloco 4",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "1º Andar",
    numeroAndar: 1,
    referencia: "Bloco 4, 1º andar, núcleo de controladoria administrativa e integridade.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["nucad", "nudac", "controladoria", "controle administrativo", "integridade", "bloco 4", "1 andar"]
  },
  {
    id: "bloco4-compa",
    nome: "COMAP - Coordenadoria de Manutenção e Projetos",
    sigla: "COMAP",
    categoria: "bloco4",
    predio: "Bloco 4",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "1º Andar",
    numeroAndar: 1,
    referencia: "Bloco 4, 1º andar, coordenadoria de manutenção e projetos de infraestrutura.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["comap", "compa", "manutencao", "projetos", "bloco 4", "1 andar"]
  },
  {
    id: "bloco4-dimoc",
    nome: "DIMIP - Divisão de Manutenção e Instalações Prediais",
    sigla: "DIMIP",
    categoria: "bloco4",
    predio: "Bloco 4",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "1º Andar",
    numeroAndar: 1,
    referencia: "Bloco 4, 1º andar, divisão responsável pela manutenção predial e instalações.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["dimip", "dimoc", "manutencao predial", "instalacoes", "bloco 4", "1 andar"]
  },
  {
    id: "bloco4-diopre",
    nome: "DIOPE - Divisão de Gerenciamento de Obras e Projetos de Engenharia",
    sigla: "DIOPE",
    categoria: "bloco4",
    predio: "Bloco 4",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "1º Andar",
    numeroAndar: 1,
    referencia: "Bloco 4, 1º andar, área de gerenciamento de obras e projetos de engenharia.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["diopre", "obras", "engenharia", "projetos", "bloco 4", "1 andar"]
  },
  {
    id: "bloco4-comat",
    nome: "COMAT - Coordenadoria de Material e Logística",
    sigla: "COMAT",
    categoria: "bloco4",
    predio: "Bloco 4",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "2º Andar",
    numeroAndar: 2,
    referencia: "Bloco 4, 2º andar, setor de material e logística institucional.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["comat", "material", "logistica", "bloco 4", "2 andar"]
  },
  {
    id: "bloco4-colic",
    nome: "COLIC - Coordenadoria de Licitação e Contratos",
    sigla: "COLIC",
    categoria: "bloco4",
    predio: "Bloco 4",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "2º Andar",
    numeroAndar: 2,
    referencia: "Bloco 4, 2º andar, área de licitações, contratos e compras institucionais.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["colic", "licitacao", "contratos", "compras", "bloco 4", "2 andar"]
  },
  {
    id: "forum-belem-subsolo",
    nome: "Fórum de Belém - Subsolo",
    sigla: "Garagem",
    categoria: "forum",
    predio: "Fórum de Belém",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "Subsolo",
    numeroAndar: -1,
    referencia: "Fórum de Belém, subsolo, área de garagem e estacionamento.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["forum de belem", "subsolo", "garagem", "estacionamento"]
  },
  {
    id: "forum-belem-terreo",
    nome: "Fórum de Belém - Térreo",
    sigla: "Fórum",
    categoria: "forum",
    predio: "Fórum de Belém",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "Térreo",
    numeroAndar: 0,
    referencia: "Fórum de Belém, térreo, hall de entrada e recepção.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["forum de belem", "terreo", "hall", "recepcao"]
  },
  {
    id: "forum-belem-1andar",
    nome: "CEIJU / 1º Andar do Fórum de Belém",
    sigla: "CEIJU",
    categoria: "forum",
    predio: "Fórum de Belém",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "1º Andar",
    numeroAndar: 1,
    referencia: "Fórum de Belém, 1º andar, área de apoio de secretaria e atendimentos do primeiro pavimento.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["ceiju", "forum", "1 andar", "belem"]
  },
  {
    id: "forum-belem-2andar-oab",
    nome: "OAB / Sala de Apoio à Advocacia",
    sigla: "OAB",
    categoria: "forum",
    predio: "Fórum de Belém",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "2º Andar",
    numeroAndar: 2,
    referencia: "Fórum de Belém, 2º andar, sala de apoio e atendimento à advocacia.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["oab", "advogados", "forum", "2 andar"]
  },
  {
    id: "forum-belem-2andar-atep",
    nome: "ATEP",
    sigla: "ATEP",
    categoria: "forum",
    predio: "Fórum de Belém",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "2º Andar",
    numeroAndar: 2,
    referencia: "Fórum de Belém, 2º andar, atendimento e suporte de unidade operacional.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["atep", "forum", "2 andar"]
  },
  {
    id: "forum-belem-2andar-vt",
    nome: "Vara do Trabalho",
    sigla: "VT",
    categoria: "varas",
    predio: "Fórum de Belém",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "2º Andar",
    numeroAndar: 2,
    referencia: "Fórum de Belém, 2º andar, área das varas do trabalho.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["vara do trabalho", "vt", "forum", "2", "2a", "segunda", "2 andar"]
  },
  {
    id: "forum-belem-3andar-vt2",
    nome: "2ª Vara do Trabalho",
    sigla: "2ª VT",
    categoria: "varas",
    predio: "Fórum de Belém",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "3º Andar",
    numeroAndar: 3,
    referencia: "Fórum de Belém, 3º andar, 2ª vara do trabalho.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["2", "2a", "segunda", "2 vara", "2ª vara", "vt2", "forum", "3 andar"]
  },
  {
    id: "forum-belem-3andar-vt3",
    nome: "3ª Vara do Trabalho",
    sigla: "3ª VT",
    categoria: "varas",
    predio: "Fórum de Belém",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "3º Andar",
    numeroAndar: 3,
    referencia: "Fórum de Belém, 3º andar, 3ª vara do trabalho.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["3", "3a", "terceira", "3 vara", "3ª vara", "vt3", "forum", "3 andar"]
  },
  {
    id: "forum-belem-4andar-vt4",
    nome: "4ª Vara do Trabalho",
    sigla: "4ª VT",
    categoria: "varas",
    predio: "Fórum de Belém",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "4º Andar",
    numeroAndar: 4,
    referencia: "Fórum de Belém, 4º andar, 4ª vara do trabalho.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["4", "4a", "quarta", "4 vara", "4ª vara", "vt4", "forum", "4 andar"]
  },
  {
    id: "forum-belem-4andar-vt5",
    nome: "5ª Vara do Trabalho",
    sigla: "5ª VT",
    categoria: "varas",
    predio: "Fórum de Belém",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "4º Andar",
    numeroAndar: 4,
    referencia: "Fórum de Belém, 4º andar, 5ª vara do trabalho.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["5", "5a", "quinta", "5 vara", "5ª vara", "vt5", "forum", "4 andar"]
  },
  {
    id: "forum-belem-5andar-vt6",
    nome: "6ª Vara do Trabalho",
    sigla: "6ª VT",
    categoria: "varas",
    predio: "Fórum de Belém",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "5º Andar",
    numeroAndar: 5,
    referencia: "Fórum de Belém, 5º andar, 6ª vara do trabalho.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["6", "6a", "sexta", "6 vara", "6ª vara", "vt6", "forum", "5 andar"]
  },
  {
    id: "forum-belem-5andar-vt7",
    nome: "7ª Vara do Trabalho",
    sigla: "7ª VT",
    categoria: "varas",
    predio: "Fórum de Belém",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "5º Andar",
    numeroAndar: 5,
    referencia: "Fórum de Belém, 5º andar, 7ª vara do trabalho.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["7", "7a", "setima", "7 vara", "7ª vara", "vt7", "forum", "5 andar"]
  },
  {
    id: "forum-belem-6andar-vt8",
    nome: "8ª Vara do Trabalho",
    sigla: "8ª VT",
    categoria: "varas",
    predio: "Fórum de Belém",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "6º Andar",
    numeroAndar: 6,
    referencia: "Fórum de Belém, 6º andar, 8ª vara do trabalho.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["8", "8a", "oitava", "8 vara", "8ª vara", "vt8", "forum", "6 andar"]
  },
  {
    id: "forum-belem-6andar-vt9",
    nome: "9ª Vara do Trabalho",
    sigla: "9ª VT",
    categoria: "varas",
    predio: "Fórum de Belém",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "6º Andar",
    numeroAndar: 6,
    referencia: "Fórum de Belém, 6º andar, 9ª vara do trabalho.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["9", "9a", "nona", "9 vara", "9ª vara", "vt9", "forum", "6 andar"]
  },
  {
    id: "forum-belem-7andar-vt10",
    nome: "10ª Vara do Trabalho",
    sigla: "10ª VT",
    categoria: "varas",
    predio: "Fórum de Belém",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "7º Andar",
    numeroAndar: 7,
    referencia: "Fórum de Belém, 7º andar, 10ª vara do trabalho.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["10", "10a", "decima", "10 vara", "10ª vara", "vt10", "forum", "7 andar"]
  },
  {
    id: "forum-belem-7andar-vt11",
    nome: "11ª Vara do Trabalho",
    sigla: "11ª VT",
    categoria: "varas",
    predio: "Fórum de Belém",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "7º Andar",
    numeroAndar: 7,
    referencia: "Fórum de Belém, 7º andar, 11ª vara do trabalho.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["11", "11a", "decima primeira", "11 vara", "11ª vara", "vt11", "forum", "7 andar"]
  },
  {
    id: "forum-belem-8andar-vt12",
    nome: "12ª Vara do Trabalho",
    sigla: "12ª VT",
    categoria: "varas",
    predio: "Fórum de Belém",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "8º Andar",
    numeroAndar: 8,
    referencia: "Fórum de Belém, 8º andar, 12ª vara do trabalho.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["12", "12a", "decima segunda", "12 vara", "12ª vara", "vt12", "forum", "8 andar"]
  },
  {
    id: "forum-belem-8andar-vt13",
    nome: "13ª Vara do Trabalho",
    sigla: "13ª VT",
    categoria: "varas",
    predio: "Fórum de Belém",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "8º Andar",
    numeroAndar: 8,
    referencia: "Fórum de Belém, 8º andar, 13ª vara do trabalho.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["13", "13a", "decima terceira", "13 vara", "13ª vara", "vt13", "forum", "8 andar"]
  },
  {
    id: "forum-belem-9andar-vt14",
    nome: "14ª Vara do Trabalho",
    sigla: "14ª VT",
    categoria: "varas",
    predio: "Fórum de Belém",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "9º Andar",
    numeroAndar: 9,
    referencia: "Fórum de Belém, 9º andar, 14ª vara do trabalho.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["14", "14a", "decima quarta", "14 vara", "14ª vara", "vt14", "forum", "9 andar"]
  },
  {
    id: "forum-belem-9andar-vt15",
    nome: "15ª Vara do Trabalho",
    sigla: "15ª VT",
    categoria: "varas",
    predio: "Fórum de Belém",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "9º Andar",
    numeroAndar: 9,
    referencia: "Fórum de Belém, 9º andar, 15ª vara do trabalho.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["15", "15a", "decima quinta", "15 vara", "15ª vara", "vt15", "forum", "9 andar"]
  },
  {
    id: "forum-belem-10andar-vt16",
    nome: "16ª Vara do Trabalho",
    sigla: "16ª VT",
    categoria: "varas",
    predio: "Fórum de Belém",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "10º Andar",
    numeroAndar: 10,
    referencia: "Fórum de Belém, 10º andar, 16ª vara do trabalho.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["16", "16a", "decima sexta", "16 vara", "16ª vara", "vt16", "forum", "10 andar"]
  },
  {
    id: "forum-belem-10andar-vt17",
    nome: "17ª Vara do Trabalho",
    sigla: "17ª VT",
    categoria: "varas",
    predio: "Fórum de Belém",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "10º Andar",
    numeroAndar: 10,
    referencia: "Fórum de Belém, 10º andar, 17ª vara do trabalho.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["17", "17a", "decima setima", "17 vara", "17ª vara", "vt17", "forum", "10 andar"]
  },
  {
    id: "forum-belem-11andar-vt18",
    nome: "18ª Vara do Trabalho",
    sigla: "18ª VT",
    categoria: "varas",
    predio: "Fórum de Belém",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "11º Andar",
    numeroAndar: 11,
    referencia: "Fórum de Belém, 11º andar, 18ª vara do trabalho.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["18", "18a", "decima oitava", "18 vara", "18ª vara", "vt18", "forum", "11 andar"]
  },
  {
    id: "forum-belem-11andar-vt19",
    nome: "19ª Vara do Trabalho",
    sigla: "19ª VT",
    categoria: "varas",
    predio: "Fórum de Belém",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "11º Andar",
    numeroAndar: 11,
    referencia: "Fórum de Belém, 11º andar, 19ª vara do trabalho.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["19", "19a", "decima nona", "19 vara", "19ª vara", "vt19", "forum", "11 andar"]
  },
  {
    id: "sede-terreo-caten",
    nome: "CATEN - Central de Atendimento",
    sigla: "CATEN",
    categoria: "sede",
    predio: "Edifício Sede",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "Térreo",
    numeroAndar: 0,
    referencia: "Edifício Sede, térreo, central de atendimento ao público.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["caten", "central de atendimento", "sede", "terreo"]
  },
  {
    id: "sede-terreo-pje",
    nome: "Divisão de Apoio ao PJe",
    sigla: "PJe",
    categoria: "sede",
    predio: "Edifício Sede",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "Térreo",
    numeroAndar: 0,
    referencia: "Edifício Sede, térreo, apoio ao sistema PJe.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["pje", "sistema", "sede", "terreo"]
  },
  {
    id: "sede-terreo-cofaz",
    nome: "COFAZ - Coordenadoria de Execução da Fazenda Pública",
    sigla: "COFAZ",
    categoria: "sede",
    predio: "Edifício Sede",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "Térreo",
    numeroAndar: 0,
    referencia: "Edifício Sede, térreo, execução de ações da Fazenda Pública.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["cofaz", "fazenda publica", "execucao", "sede", "terreo"]
  },
  {
    id: "sede-terreo-difre",
    nome: "DIPRE - Divisão de Precatórios",
    sigla: "DIPRE",
    categoria: "sede",
    predio: "Edifício Sede",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "Térreo",
    numeroAndar: 0,
    referencia: "Edifício Sede, térreo, divisão responsável pelo atendimento e processamento de precatórios.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["dipre", "precatórios", "precatorios", "sede", "terreo"]
  },
  {
    id: "sede-terreo-dejt",
    nome: "DEJT - Diário Eletrônico e Digitalização de Documentos",
    sigla: "DEJT",
    categoria: "sede",
    predio: "Edifício Sede",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "Térreo",
    numeroAndar: 0,
    referencia: "Edifício Sede, térreo, Diário Eletrônico e área de digitalização de documentos.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["dejt", "diario eletronico", "digitalizacao", "documentos", "sede", "terreo"]
  },
  {
    id: "sede-terreo-cexec",
    nome: "CEXEC - Central de Execução",
    sigla: "CEXEC",
    categoria: "sede",
    predio: "Edifício Sede",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "Térreo",
    numeroAndar: 0,
    referencia: "Edifício Sede, térreo, Central de Execução.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["cexec", "central de execucao", "execucao", "sede", "terreo"]
  },
  {
    id: "sede-terreo-coins",
    nome: "COINS - Coordenadoria de Infraestrutura e Suporte a SETIN",
    sigla: "COINS",
    categoria: "sede",
    predio: "Edifício Sede",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "Térreo",
    numeroAndar: 0,
    referencia: "Edifício Sede, térreo, Coordenadoria de Infraestrutura e Suporte a SETIN.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["coins", "setin", "infraestrutura", "suporte", "tecnologia", "sede", "terreo"]
  },
  {
    id: "sede-terreo-oficiais-justica",
    nome: "Oficiais de Justiça",
    sigla: "Oficiais",
    categoria: "sede",
    predio: "Edifício Sede",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "Térreo",
    numeroAndar: 0,
    referencia: "Edifício Sede, térreo, área de atendimento dos Oficiais de Justiça.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["oficiais de justica", "oficiais", "justica", "sede", "terreo"]
  },
  {
    id: "sede-1andar-espaco-cultural",
    nome: "Espaço Cultural",
    sigla: "Cultura",
    categoria: "sede",
    predio: "Edifício Sede",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "1º Andar",
    numeroAndar: 1,
    referencia: "Edifício Sede, 1º andar, espaço para eventos culturais e atividades institucionais.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["espaco cultural", "cultura", "sede", "1 andar"]
  },
  {
    id: "sede-1andar-sejud",
    nome: "SEJUD - Secretaria Geral Judiciária",
    sigla: "SEJUD",
    categoria: "sede",
    predio: "Edifício Sede",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "1º Andar",
    numeroAndar: 1,
    referencia: "Edifício Sede, 1º andar, secretaria geral judiciária do tribunal.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["sejud", "secretaria geral judiciaria", "sede", "1 andar"]
  },
  {
    id: "sede-1andar-astecj",
    nome: "ASTECJUD - Assessoria Técnica da Secretaria Geral Judiciária",
    sigla: "ASTECJUD",
    categoria: "sede",
    predio: "Edifício Sede",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "1º Andar",
    numeroAndar: 1,
    referencia: "Edifício Sede, 1º andar, assessoria técnica administrativa e judiciária.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["astecj", "assessoria tecnica", "sejud", "sede", "1 andar"]
  },
  {
    id: "sede-1andar-cojud",
    nome: "COJUD - Coordenadoria de Apoio Judiciário",
    sigla: "COJUD",
    categoria: "sede",
    predio: "Edifício Sede",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "1º Andar",
    numeroAndar: 1,
    referencia: "Edifício Sede, 1º andar, Coordenadoria de Apoio Judiciário.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["cojud", "apoio judiciario", "sejud", "sede", "1 andar"]
  },
  {
    id: "sede-2andar-gabinetes-desembargadores",
    nome: "Gabinetes dos Desembargadores",
    sigla: "Gabinetes",
    categoria: "sede",
    predio: "Edifício Sede",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "2º Andar",
    numeroAndar: 2,
    referencia: "Edifício Sede, 2º andar, gabinetes dos desembargadores do TRT-8.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["gabinetes", "desembargadores", "sede", "2 andar"]
  },
  {
    id: "sede-2andar-cocor",
    nome: "COCOR - Coordenadoria de Criminal e Eventos",
    sigla: "COCOR",
    categoria: "sede",
    predio: "Edifício Sede",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "2º Andar",
    numeroAndar: 2,
    referencia: "Edifício Sede, 2º andar, coordenadoria criminal e de eventos.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["cocor", "criminal", "eventos", "sede", "2 andar"]
  },
  {
    id: "sede-3andar-presidencia",
    nome: "Presidência",
    sigla: "PRESI",
    categoria: "sede",
    predio: "Edifício Sede",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "3º Andar",
    numeroAndar: 3,
    referencia: "Edifício Sede, 3º andar, presidência do tribunal.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["presidencia", "sede", "3 andar"]
  },
  {
    id: "sede-3andar-serer",
    nome: "SERER - Secretaria do Recurso de Revistas",
    sigla: "SERER",
    categoria: "sede",
    predio: "Edifício Sede",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "3º Andar",
    numeroAndar: 3,
    referencia: "Edifício Sede, 3º andar, secretaria do recurso de revistas.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["serer", "recurso de revistas", "sede", "3 andar"]
  },
  {
    id: "sede-3andar-vipre",
    nome: "VIPRE - Vice-Presidência",
    sigla: "VIPRE",
    categoria: "sede",
    predio: "Edifício Sede",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "3º Andar",
    numeroAndar: 3,
    referencia: "Edifício Sede, 3º andar, vice-presidência do tribunal.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["vipre", "vice presidencia", "sede", "3 andar"]
  },
  {
    id: "sede-3andar-corr",
    nome: "COR08 - Corregedoria Regional",
    sigla: "COR08",
    categoria: "sede",
    predio: "Edifício Sede",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "3º Andar",
    numeroAndar: 3,
    referencia: "Edifício Sede, 3º andar, corregedoria regional do TRT-8.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["cor08", "correg", "corregedoria", "sede", "3 andar"]
  },
  {
    id: "sede-3andar-asjur",
    nome: "ASJUR - Assessoria Jurídica",
    sigla: "ASJUR",
    categoria: "sede",
    predio: "Edifício Sede",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "3º Andar",
    numeroAndar: 3,
    referencia: "Edifício Sede, 3º andar, assessoria jurídica.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["asjur", "juridica", "assessoria", "sede", "3 andar"]
  },
  {
    id: "sede-1andar-coape",
    nome: "COAPE - Coordenadoria de Apoio ao Tribunal Pleno, Seções Especializadas e Conciliação",
    sigla: "COAPE",
    categoria: "sede",
    predio: "Edifício Sede",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "1º Andar",
    numeroAndar: 1,
    referencia: "Edifício Sede, 1º andar, apoio ao Tribunal Pleno, seções especializadas e conciliação.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["coape", "tribunal pleno", "secoes especializadas", "conciliacao", "sede", "1 andar"]
  },
  {
    id: "sede-1andar-salas-sessoes",
    nome: "Salas de Sessões de Turmas e Pleno",
    sigla: "Sessões",
    categoria: "sede",
    predio: "Edifício Sede",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "1º Andar",
    numeroAndar: 1,
    referencia: "Edifício Sede, 1º andar, salas de sessões das Turmas e do Pleno.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["salas de sessoes", "turmas", "pleno", "sede", "1 andar"]
  },
  {
    id: "sede-1andar-biblioteca",
    nome: "Biblioteca",
    sigla: "Biblioteca",
    categoria: "sede",
    predio: "Edifício Sede",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "1º Andar",
    numeroAndar: 1,
    referencia: "Edifício Sede, 1º andar, biblioteca institucional.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["biblioteca", "sede", "1 andar"]
  },
  {
    id: "sede-2andar-cocer",
    nome: "COCER - Coordenadoria de Cerimonial e Eventos",
    sigla: "COCER",
    categoria: "sede",
    predio: "Edifício Sede",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "2º Andar",
    numeroAndar: 2,
    referencia: "Edifício Sede, 2º andar, Coordenadoria de Cerimonial e Eventos.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["cocer", "cerimonial", "eventos", "sede", "2 andar"]
  },
  {
    id: "sede-4andar-setin",
    nome: "SETIN - Secretaria de Tecnologia da Informação",
    sigla: "SETIN",
    categoria: "sede",
    predio: "Edifício Sede",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "4º Andar",
    numeroAndar: 4,
    referencia: "Edifício Sede, 4º andar, Secretaria de Tecnologia da Informação, vinculada à COINS.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["setin", "tecnologia da informacao", "ti", "coins", "sede", "4 andar"]
  },
  {
    id: "sede-4andar-sala-nobre",
    nome: "Sala Nobre",
    sigla: "Sala Nobre",
    categoria: "sede",
    predio: "Edifício Sede",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "4º Andar",
    numeroAndar: 4,
    referencia: "Edifício Sede, 4º andar, Sala Nobre.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["sala nobre", "sede", "4 andar"]
  },
  {
    id: "bloco2-terreo-dimov",
    nome: "DIMOV - Divisão de Provimentos e Movimentação de Servidores",
    sigla: "DIMOV",
    categoria: "bloco2",
    predio: "Bloco 2",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "Térreo",
    numeroAndar: 0,
    referencia: "Bloco 2, térreo, Divisão de Provimentos e Movimentação de Servidores.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["dimov", "provimentos", "movimentacao", "servidores", "bloco 2", "terreo"]
  },
  {
    id: "bloco3-terreo-liods",
    nome: "LIODS - Laboratório de Inovação, Inteligência e Objetivos de Desenvolvimento Sustentável",
    sigla: "LIODS",
    categoria: "bloco3",
    predio: "Bloco 3",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "Térreo",
    numeroAndar: 0,
    referencia: "Bloco 3, térreo, Laboratório de Inovação, Inteligência e Objetivos de Desenvolvimento Sustentável.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["liods", "inovacao", "inteligencia", "desenvolvimento sustentavel", "bloco 3", "terreo"]
  },
  {
    id: "bloco3-terreo-dias",
    nome: "DIAS - Divisão de Acessibilidade, Inclusão e Sustentabilidade",
    sigla: "DIAS",
    categoria: "bloco3",
    predio: "Bloco 3",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "Térreo",
    numeroAndar: 0,
    referencia: "Bloco 3, térreo, Divisão de Acessibilidade, Inclusão e Sustentabilidade.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["dias", "acessibilidade", "inclusao", "sustentabilidade", "bloco 3", "terreo"]
  },
  {
    id: "bloco3-terreo-seamb",
    nome: "SEAMB - Seção de Sustentabilidade",
    sigla: "SEAMB",
    categoria: "bloco3",
    predio: "Bloco 3",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "Térreo",
    numeroAndar: 0,
    referencia: "Bloco 3, térreo, Seção de Sustentabilidade.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["seamb", "sustentabilidade", "dias", "bloco 3", "terreo"]
  },
  {
    id: "bloco3-1andar-dsei",
    nome: "DSEI - Sala de Treinamento DSEI",
    sigla: "DSEI",
    categoria: "bloco3",
    predio: "Bloco 3",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "1º Andar",
    numeroAndar: 1,
    referencia: "Bloco 3, 1º andar, sala de treinamento do DSEI.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["dsei", "sala de treinamento", "treinamento", "bloco 3", "1 andar"]
  },
  {
    id: "bloco3-1andar-mpt",
    nome: "MPT - Ministério Público do Trabalho",
    sigla: "MPT",
    categoria: "bloco3",
    predio: "Bloco 3",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "1º Andar",
    numeroAndar: 1,
    referencia: "Bloco 3, 1º andar, Ministério Público do Trabalho.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["mpt", "ministerio publico do trabalho", "bloco 3", "1 andar"]
  },
  {
    id: "bloco3-1andar-treinamento-codse",
    nome: "Sala de Treinamento da CODSE",
    sigla: "CODSE Treinamento",
    categoria: "bloco3",
    predio: "Bloco 3",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "1º Andar",
    numeroAndar: 1,
    referencia: "Bloco 3, 1º andar, sala de treinamento da CODSE.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["sala de treinamento codse", "codse", "treinamento", "bloco 3", "1 andar"]
  },
  {
    id: "bloco3-2andar-seges",
    nome: "SEGES - Secretaria de Governança e Gestão Estratégica",
    sigla: "SEGES",
    categoria: "bloco3",
    predio: "Bloco 3",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "2º Andar",
    numeroAndar: 2,
    referencia: "Bloco 3, 2º andar, Secretaria de Governança e Gestão Estratégica.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["seges", "governanca", "gestao estrategica", "bloco 3", "2 andar"]
  },
  {
    id: "bloco3-2andar-seaud",
    nome: "SEAUD - Secretaria de Auditoria",
    sigla: "SEAUD",
    categoria: "bloco3",
    predio: "Bloco 3",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "2º Andar",
    numeroAndar: 2,
    referencia: "Bloco 3, 2º andar, Secretaria de Auditoria.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["seaud", "auditoria", "secon", "seati", "seafi", "seape", "bloco 3", "2 andar"]
  },
  {
    id: "bloco3-2andar-secon",
    nome: "SECON - Seção de Auditoria de Contratações",
    sigla: "SECON",
    categoria: "bloco3",
    predio: "Bloco 3",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "2º Andar",
    numeroAndar: 2,
    referencia: "Bloco 3, 2º andar, Seção de Auditoria de Contratações.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["secon", "auditoria", "contratacoes", "seaud", "bloco 3", "2 andar"]
  },
  {
    id: "bloco3-2andar-seati",
    nome: "SeATI - Seção de Auditoria de Tecnologia da Informação e Comunicação",
    sigla: "SeATI",
    categoria: "bloco3",
    predio: "Bloco 3",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "2º Andar",
    numeroAndar: 2,
    referencia: "Bloco 3, 2º andar, Seção de Auditoria de Tecnologia da Informação e Comunicação.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["seati", "auditoria", "tecnologia da informacao", "comunicacao", "seaud", "bloco 3", "2 andar"]
  },
  {
    id: "bloco3-2andar-seafi",
    nome: "SeAFI - Seção de Auditoria Financeira",
    sigla: "SeAFI",
    categoria: "bloco3",
    predio: "Bloco 3",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "2º Andar",
    numeroAndar: 2,
    referencia: "Bloco 3, 2º andar, Seção de Auditoria Financeira.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["seafi", "auditoria", "financeira", "seaud", "bloco 3", "2 andar"]
  },
  {
    id: "bloco3-2andar-seape",
    nome: "SeAPE - Seção de Auditoria de Gestão de Pessoas",
    sigla: "SeAPE",
    categoria: "bloco3",
    predio: "Bloco 3",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "2º Andar",
    numeroAndar: 2,
    referencia: "Bloco 3, 2º andar, Seção de Auditoria de Gestão de Pessoas.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["seape", "auditoria", "gestao de pessoas", "seaud", "bloco 3", "2 andar"]
  },
  {
    id: "bloco3-3andar-sepag",
    nome: "SEPAG - Secretaria de Pagamento e Folha",
    sigla: "SEPAG",
    categoria: "bloco3",
    predio: "Bloco 3",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "3º Andar",
    numeroAndar: 3,
    referencia: "Bloco 3, 3º andar, Secretaria de Pagamento e Folha.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["sepag", "pagamento", "folha", "bloco 3", "3 andar"]
  },
  {
    id: "bloco3-3andar-nupag",
    nome: "NUPAG - Núcleo de Pagamento",
    sigla: "NUPAG",
    categoria: "bloco3",
    predio: "Bloco 3",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "3º Andar",
    numeroAndar: 3,
    referencia: "Bloco 3, 3º andar, Núcleo de Pagamento.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["nupag", "pagamento", "bloco 3", "3 andar"]
  },
  {
    id: "bloco3-3andar-dicea",
    nome: "DICEA - Divisão de Combate ao Trabalho Infantil e Estímulo à Aprendizagem",
    sigla: "DICEA",
    categoria: "bloco3",
    predio: "Bloco 3",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "3º Andar",
    numeroAndar: 3,
    referencia: "Bloco 3, 3º andar, Divisão de Combate ao Trabalho Infantil e Estímulo à Aprendizagem.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["dicea", "trabalho infantil", "aprendizagem", "bloco 3", "3 andar"]
  },
  {
    id: "bloco3-3andar-dipag",
    nome: "DIPAG - Divisão de Pagamento de Servidores, Aposentados e Pensionistas",
    sigla: "DIPAG",
    categoria: "bloco3",
    predio: "Bloco 3",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "3º Andar",
    numeroAndar: 3,
    referencia: "Bloco 3, 3º andar, Divisão de Pagamento de Servidores, Aposentados e Pensionistas.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["dipag", "pagamento", "servidores", "aposentados", "pensionistas", "bloco 3", "3 andar"]
  },
  {
    id: "bloco3-3andar-aspag",
    nome: "ASPAG - Assessoria de Gestão de Dados do Secretariado de Pessoal",
    sigla: "ASPAG",
    categoria: "bloco3",
    predio: "Bloco 3",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "3º Andar",
    numeroAndar: 3,
    referencia: "Bloco 3, 3º andar, Assessoria de Gestão de Dados do Secretariado de Pessoal.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["aspag", "gestao de dados", "pessoal", "bloco 3", "3 andar"]
  },
  {
    id: "bloco3-3andar-dipam",
    nome: "DIPAM - Divisão de Pagamento de Magistrados",
    sigla: "DIPAM",
    categoria: "bloco3",
    predio: "Bloco 3",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "3º Andar",
    numeroAndar: 3,
    referencia: "Bloco 3, 3º andar, Divisão de Pagamento de Magistrados.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["dipam", "pagamento", "magistrados", "bloco 3", "3 andar"]
  },
  {
    id: "bloco3-3andar-coepp",
    nome: "COEPP - Coordenadoria de Escritório de Projetos e Processos",
    sigla: "COEPP",
    categoria: "bloco3",
    predio: "Bloco 3",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "3º Andar",
    numeroAndar: 3,
    referencia: "Bloco 3, 3º andar, Coordenadoria de Escritório de Projetos e Processos.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["coepp", "projetos", "processos", "bloco 3", "3 andar"]
  },
  {
    id: "bloco3-3andar-seinv",
    nome: "SeINV - Seção de Inovação",
    sigla: "SeINV",
    categoria: "bloco3",
    predio: "Bloco 3",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "3º Andar",
    numeroAndar: 3,
    referencia: "Bloco 3, 3º andar, Seção de Inovação.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["seinv", "inovacao", "coepp", "bloco 3", "3 andar"]
  },
  {
    id: "bloco3-3andar-sepro",
    nome: "SePRO - Seção de Gestão de Processos",
    sigla: "SePRO",
    categoria: "bloco3",
    predio: "Bloco 3",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "3º Andar",
    numeroAndar: 3,
    referencia: "Bloco 3, 3º andar, Seção de Gestão de Processos.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["sepro", "gestao de processos", "coepp", "bloco 3", "3 andar"]
  },
  {
    id: "bloco3-3andar-seric",
    nome: "SeRIC - Seção de Gestão de Riscos",
    sigla: "SeRIC",
    categoria: "bloco3",
    predio: "Bloco 3",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "3º Andar",
    numeroAndar: 3,
    referencia: "Bloco 3, 3º andar, Seção de Gestão de Riscos.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["seric", "gestao de riscos", "digov", "bloco 3", "3 andar"]
  },
  {
    id: "bloco3-3andar-digov",
    nome: "DIGOV - Divisão de Apoio à Governança",
    sigla: "DIGOV",
    categoria: "bloco3",
    predio: "Bloco 3",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "3º Andar",
    numeroAndar: 3,
    referencia: "Bloco 3, 3º andar, Divisão de Apoio à Governança.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["digov", "governanca", "bloco 3", "3 andar"]
  },
  {
    id: "bloco3-3andar-diest",
    nome: "DIEST - Divisão de Estatística e Ciência de Dados",
    sigla: "DIEST",
    categoria: "bloco3",
    predio: "Bloco 3",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "3º Andar",
    numeroAndar: 3,
    referencia: "Bloco 3, 3º andar, Divisão de Estatística e Ciência de Dados.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["diest", "estatistica", "ciencia de dados", "bloco 3", "3 andar"]
  },
  {
    id: "bloco4-3andar-seadm",
    nome: "SEADM - Secretaria Administrativa",
    sigla: "SEADM",
    categoria: "bloco4",
    predio: "Bloco 4",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "3º Andar",
    numeroAndar: 3,
    referencia: "Bloco 4, 3º andar, Secretaria Administrativa.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["seadm", "administrativa", "bloco 4", "3 andar"]
  },
  {
    id: "bloco4-3andar-dicon",
    nome: "DICON - Divisão de Contabilidade e Conformidade dos Atos de Gestão",
    sigla: "DICON",
    categoria: "bloco4",
    predio: "Bloco 4",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "3º Andar",
    numeroAndar: 3,
    referencia: "Bloco 4, 3º andar, Divisão de Contabilidade e Conformidade dos Atos de Gestão.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["dicon", "contabilidade", "conformidade", "atos de gestao", "bloco 4", "3 andar"]
  },
  {
    id: "bloco4-3andar-digef",
    nome: "DIGEF - Divisão de Gestão e Fiscalização de Contratos",
    sigla: "DIGEF",
    categoria: "bloco4",
    predio: "Bloco 4",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "3º Andar",
    numeroAndar: 3,
    referencia: "Bloco 4, 3º andar, Divisão de Gestão e Fiscalização de Contratos.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["digef", "gestao", "fiscalizacao", "contratos", "bloco 4", "3 andar"]
  },
  {
    id: "bloco4-3andar-dicot",
    nome: "DIGOC - Divisão de Apoio e Governança de Contratações em Geral",
    sigla: "DIGOC",
    categoria: "bloco4",
    predio: "Bloco 4",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "3º Andar",
    numeroAndar: 3,
    referencia: "Bloco 4, 3º andar, Divisão de Apoio e Governança de Contratações em Geral.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["digoc", "dicot", "contratacoes", "governanca", "bloco 4", "3 andar"]
  },
  {
    id: "bloco4-3andar-cofin",
    nome: "COFIN - Coordenadoria de Orçamento e Finanças",
    sigla: "COFIN",
    categoria: "bloco4",
    predio: "Bloco 4",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "3º Andar",
    numeroAndar: 3,
    referencia: "Bloco 4, 3º andar, Coordenadoria de Orçamento e Finanças.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["cofin", "orcamento", "financas", "bloco 4", "3 andar"]
  },
  {
    id: "bloco4-3andar-dilip",
    nome: "DILIP - Divisão de Liquidação e Pagamento",
    sigla: "DILIP",
    categoria: "bloco4",
    predio: "Bloco 4",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "3º Andar",
    numeroAndar: 3,
    referencia: "Bloco 4, 3º andar, Divisão de Liquidação e Pagamento.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["dilip", "liquidacao", "pagamento", "bloco 4", "3 andar"]
  },
  {
    id: "bloco4-3andar-nuorc",
    nome: "NUORC - Núcleo de Execução Orçamentária",
    sigla: "NUORC",
    categoria: "bloco4",
    predio: "Bloco 4",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "3º Andar",
    numeroAndar: 3,
    referencia: "Bloco 4, 3º andar, Núcleo de Execução Orçamentária.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["nuorc", "execucao orcamentaria", "orcamento", "bloco 4", "3 andar"]
  },
  {
    id: "bloco4-3andar-nupla",
    nome: "NUPLA - Núcleo de Planejamento Orçamentário",
    sigla: "NUPLA",
    categoria: "bloco4",
    predio: "Bloco 4",
    endereco: "Tribunal Regional do Trabalho da 8ª Região - Belém",
    andar: "3º Andar",
    numeroAndar: 3,
    referencia: "Bloco 4, 3º andar, Núcleo de Planejamento Orçamentário.",
    telefone: "-",
    ramal: "-",
    email: "-",
    juizTitular: "-",
    diretor: "-",
    tags: ["nupla", "planejamento orcamentario", "orcamento", "bloco 4", "3 andar"]
  }
];


function carregarLocaisCompletos() {
  const locaisSalvos = localStorage.getItem("trt8_locais_db");
  if (locaisSalvos) {
    try {
      const parsed = JSON.parse(locaisSalvos);
      if (Array.isArray(parsed) && parsed.length > 0) {
        const temModeloAtual = parsed.some(loc => loc && loc.id === "sede-1andar-cojud");
        if (temModeloAtual) {
          return parsed;
        }
      }
    } catch (e) {
      console.warn("Erro ao ler dados do localStorage, usando iniciais:", e);
    }
  }

  localStorage.setItem("trt8_locais_db", JSON.stringify(DADOS_LOCAIS_INICIAIS));
  return DADOS_LOCAIS_INICIAIS;
}


function salvarLocaisNoStorage(lista) {
  localStorage.setItem("trt8_locais_db", JSON.stringify(lista));
}
