/**
 * Base de Dados Oficial e Estruturada do TRT-8 (Belém)
 * Contém o mapeamento detalhado dos prédios:
 * 1. Fórum Trabalhista de Belém (Edifício Des. José Maria Quadros de Alencastro - Tv. Dom Pedro I, 698)
 * 2. Edifício-Sede do TRT-8 (Tv. Dom Pedro I, 746)
 */

const DADOS_LOCAIS_INICIAIS = [
  // --- FÓRUM TRABALHISTA: VARAS DO TRABALHO (1ª A 19ª) ---
  {
    id: "vt-01",
    nome: "1ª Vara do Trabalho de Belém",
    sigla: "1ª VT",
    categoria: "varas",
    predio: "Fórum Trabalhista (Ed. Alencastro)",
    endereco: "Tv. Dom Pedro I, nº 698",
    andar: "2º Andar",
    numeroAndar: 2,
    referencia: "Ao sair do hall dos elevadores, seguir em direção ao corredor principal do 2º andar.",
    telefone: "(91) 4008-7159",
    ramal: "7159",
    email: "vt1belem.sec@trt8.jus.br",
    juizTitular: "Amanaci Giannaccini",
    diretor: "Simone Maria Miglio Muller",
    tags: ["1", "1a", "primeira", "vara", "vt1", "audiencia", "balcao virtual"]
  },
  {
    id: "vt-02",
    nome: "2ª Vara do Trabalho de Belém",
    sigla: "2ª VT",
    categoria: "varas",
    predio: "Fórum Trabalhista (Ed. Alencastro)",
    endereco: "Tv. Dom Pedro I, nº 698",
    andar: "3º Andar",
    numeroAndar: 3,
    referencia: "3º andar, ala frontal voltada para a Tv. Dom Pedro I.",
    telefone: "(91) 4008-7111",
    ramal: "7111",
    email: "vt2belem.sec@trt8.jus.br",
    juizTitular: "Francisco Milton Araujo Junior",
    diretor: "Eduardo Mário Monteiro Oliveira",
    tags: ["2", "2a", "segunda", "vara", "vt2"]
  },
  {
    id: "vt-03",
    nome: "3ª Vara do Trabalho de Belém",
    sigla: "3ª VT",
    categoria: "varas",
    predio: "Fórum Trabalhista (Ed. Alencastro)",
    endereco: "Tv. Dom Pedro I, nº 698",
    andar: "3º Andar",
    numeroAndar: 3,
    referencia: "3º andar, ao lado da 2ª Vara do Trabalho.",
    telefone: "(91) 4008-7112",
    ramal: "7112",
    email: "vt3belem.sec@trt8.jus.br",
    juizTitular: "Léa Helena Pessoa dos Santos Sarmento",
    diretor: "Helder Benedito Carvalho Quaresma",
    tags: ["3", "3a", "terceira", "vara", "vt3"]
  },
  {
    id: "vt-04",
    nome: "4ª Vara do Trabalho de Belém",
    sigla: "4ª VT",
    categoria: "varas",
    predio: "Fórum Trabalhista (Ed. Alencastro)",
    endereco: "Tv. Dom Pedro I, nº 698",
    andar: "4º Andar",
    numeroAndar: 4,
    referencia: "4º andar, saindo do elevador vire à direita.",
    telefone: "(91) 4008-7115",
    ramal: "7115",
    email: "vt4belem.sec@trt8.jus.br",
    juizTitular: "Erika Vasconcelos de Lima Dacier Lobato",
    diretor: "Adriano Andrade do Rosário",
    tags: ["4", "4a", "quarta", "vara", "vt4"]
  },
  {
    id: "vt-05",
    nome: "5ª Vara do Trabalho de Belém",
    sigla: "5ª VT",
    categoria: "varas",
    predio: "Fórum Trabalhista (Ed. Alencastro)",
    endereco: "Tv. Dom Pedro I, nº 698",
    andar: "4º Andar",
    numeroAndar: 4,
    referencia: "4º andar, corredor em frente à 4ª Vara.",
    telefone: "(91) 4008-7160",
    ramal: "7160",
    email: "vt5belem.sec@trt8.jus.br",
    juizTitular: "João Carlos Travassos Teixeira Pinto",
    diretor: "Henrique Silva Vila Nova",
    tags: ["5", "5a", "quinta", "vara", "vt5"]
  },
  {
    id: "vt-06",
    nome: "6ª Vara do Trabalho de Belém",
    sigla: "6ª VT",
    categoria: "varas",
    predio: "Fórum Trabalhista (Ed. Alencastro)",
    endereco: "Tv. Dom Pedro I, nº 698",
    andar: "5º Andar",
    numeroAndar: 5,
    referencia: "5º andar, saindo dos elevadores à esquerda.",
    telefone: "(91) 4008-7127",
    ramal: "7127",
    email: "vt6belem.sec@trt8.jus.br",
    juizTitular: "Renata Platon Anjos",
    diretor: "Jane Márcia e Silva Cerveira",
    tags: ["6", "6a", "sexta", "vara", "vt6"]
  },
  {
    id: "vt-07",
    nome: "7ª Vara do Trabalho de Belém",
    sigla: "7ª VT",
    categoria: "varas",
    predio: "Fórum Trabalhista (Ed. Alencastro)",
    endereco: "Tv. Dom Pedro I, nº 698",
    andar: "5º Andar",
    numeroAndar: 5,
    referencia: "5º andar, em frente à 6ª Vara do Trabalho.",
    telefone: "(91) 4008-7274",
    ramal: "7274",
    email: "vt7belem.sec@trt8.jus.br",
    juizTitular: "Tereza Cristina de Almeida Cavalcante Aranha",
    diretor: "Núbia Leão Viana",
    tags: ["7", "7a", "setima", "sétima", "vara", "vt7"]
  },
  {
    id: "vt-08",
    nome: "8ª Vara do Trabalho de Belém",
    sigla: "8ª VT",
    categoria: "varas",
    predio: "Fórum Trabalhista (Ed. Alencastro)",
    endereco: "Tv. Dom Pedro I, nº 698",
    andar: "6º Andar",
    numeroAndar: 6,
    referencia: "6º andar, lado leste do corredor.",
    telefone: "(91) 4008-7152",
    ramal: "7152",
    email: "vt8belem.sec@trt8.jus.br",
    juizTitular: "Luís Antonio Nobre de Brito",
    diretor: "Júlia Sousa de Menezes",
    tags: ["8", "8a", "oitava", "vara", "vt8"]
  },
  {
    id: "vt-09",
    nome: "9ª Vara do Trabalho de Belém",
    sigla: "9ª VT",
    categoria: "varas",
    predio: "Fórum Trabalhista (Ed. Alencastro)",
    endereco: "Tv. Dom Pedro I, nº 698",
    andar: "6º Andar",
    numeroAndar: 6,
    referencia: "6º andar, lado oeste do corredor.",
    telefone: "(91) 4008-7134",
    ramal: "7134",
    email: "vt9belem.sec@trt8.jus.br",
    juizTitular: "Paulo Henrique Silva Ázar",
    diretor: "Márcia Carvalho de Mendonça",
    tags: ["9", "9a", "nona", "vara", "vt9"]
  },
  {
    id: "vt-10",
    nome: "10ª Vara do Trabalho de Belém",
    sigla: "10ª VT",
    categoria: "varas",
    predio: "Fórum Trabalhista (Ed. Alencastro)",
    endereco: "Tv. Dom Pedro I, nº 698",
    andar: "7º Andar",
    numeroAndar: 7,
    referencia: "7º andar, virando à direita no hall.",
    telefone: "(91) 4008-7086",
    ramal: "7086",
    email: "vt10belem.sec@trt8.jus.br",
    juizTitular: "Flávia Joseane Kuroda",
    diretor: "Jeanne Lima Marinho",
    tags: ["10", "10a", "decima", "décima", "vara", "vt10"]
  },
  {
    id: "vt-11",
    nome: "11ª Vara do Trabalho de Belém",
    sigla: "11ª VT",
    categoria: "varas",
    predio: "Fórum Trabalhista (Ed. Alencastro)",
    endereco: "Tv. Dom Pedro I, nº 698",
    andar: "7º Andar",
    numeroAndar: 7,
    referencia: "7º andar, virando à esquerda no hall.",
    telefone: "(91) 4008-7145",
    ramal: "7145",
    email: "vt11belem.sec@trt8.jus.br",
    juizTitular: "Océlio de Jesus C. Morais",
    diretor: "Edilberto Cardoso de Oliveira",
    tags: ["11", "11a", "decima primeira", "décima primeira", "vara", "vt11"]
  },
  {
    id: "vt-12",
    nome: "12ª Vara do Trabalho de Belém",
    sigla: "12ª VT",
    categoria: "varas",
    predio: "Fórum Trabalhista (Ed. Alencastro)",
    endereco: "Tv. Dom Pedro I, nº 698",
    andar: "8º Andar",
    numeroAndar: 8,
    referencia: "8º andar, porta principal em frente aos elevadores 1 e 2.",
    telefone: "(91) 4008-7177",
    ramal: "7177",
    email: "vt12belem.sec@trt8.jus.br",
    juizTitular: "Paulo José Alves Cavalcante",
    diretor: "Raphael Marques Barros",
    tags: ["12", "12a", "decima segunda", "décima segunda", "vara", "vt12"]
  },
  {
    id: "vt-13",
    nome: "13ª Vara do Trabalho de Belém",
    sigla: "13ª VT",
    categoria: "varas",
    predio: "Fórum Trabalhista (Ed. Alencastro)",
    endereco: "Tv. Dom Pedro I, nº 698",
    andar: "8º Andar",
    numeroAndar: 8,
    referencia: "8º andar, porta lateral ao lado da 12ª Vara.",
    telefone: "(91) 4008-7174",
    ramal: "7174",
    email: "vt13belem.sec@trt8.jus.br",
    juizTitular: "Jorge Antonio Ramos Vieira",
    diretor: "Fabrício Figueiredo da Silva",
    tags: ["13", "13a", "decima terceira", "décima terceira", "vara", "vt13"]
  },
  {
    id: "vt-14",
    nome: "14ª Vara do Trabalho de Belém",
    sigla: "14ª VT",
    categoria: "varas",
    predio: "Fórum Trabalhista (Ed. Alencastro)",
    endereco: "Tv. Dom Pedro I, nº 698",
    andar: "9º Andar",
    numeroAndar: 9,
    referencia: "9º andar, ala sul do pavimento.",
    telefone: "(91) 4008-7156",
    ramal: "7156",
    email: "vt14belem.sec@trt8.jus.br",
    juizTitular: "Marco Plínio da Silva Aranha",
    diretor: "Karlla Costa Nogueira Santos",
    tags: ["14", "14a", "decima quarta", "décima quarta", "vara", "vt14"]
  },
  {
    id: "vt-15",
    nome: "15ª Vara do Trabalho de Belém",
    sigla: "15ª VT",
    categoria: "varas",
    predio: "Fórum Trabalhista (Ed. Alencastro)",
    endereco: "Tv. Dom Pedro I, nº 698",
    andar: "9º Andar",
    numeroAndar: 9,
    referencia: "9º andar, ala norte, em frente à 14ª Vara.",
    telefone: "(91) 4008-7286",
    ramal: "7286",
    email: "vt15belem.sec@trt8.jus.br",
    juizTitular: "Paula Maria Pereira Soares",
    diretor: "Anette Nascimento Campos",
    tags: ["15", "15a", "decima quinta", "décima quinta", "vara", "vt15"]
  },
  {
    id: "vt-16",
    nome: "16ª Vara do Trabalho de Belém",
    sigla: "16ª VT",
    categoria: "varas",
    predio: "Fórum Trabalhista (Ed. Alencastro)",
    endereco: "Tv. Dom Pedro I, nº 698",
    andar: "10º Andar",
    numeroAndar: 10,
    referencia: "10º andar, saindo do elevador à esquerda.",
    telefone: "(91) 4008-7285",
    ramal: "7285",
    email: "vt16belem.sec@trt8.jus.br",
    juizTitular: "Vanilza de Souza Malcher",
    diretor: "Garnier Franco Araújo",
    tags: ["16", "16a", "decima sexta", "décima sexta", "vara", "vt16"]
  },
  {
    id: "vt-17",
    nome: "17ª Vara do Trabalho de Belém",
    sigla: "17ª VT",
    categoria: "varas",
    predio: "Fórum Trabalhista (Ed. Alencastro)",
    endereco: "Tv. Dom Pedro I, nº 698",
    andar: "10º Andar",
    numeroAndar: 10,
    referencia: "10º andar, saindo do elevador à direita.",
    telefone: "(91) 4008-7190",
    ramal: "7190",
    email: "vt17belem.sec@trt8.jus.br",
    juizTitular: "Melina Russelakis Carneiro",
    diretor: "Rodnei José Macambira Martins",
    tags: ["17", "17a", "decima setima", "décima sétima", "vara", "vt17"]
  },
  {
    id: "vt-18",
    nome: "18ª Vara do Trabalho de Belém",
    sigla: "18ª VT",
    categoria: "varas",
    predio: "Fórum Trabalhista (Ed. Alencastro)",
    endereco: "Tv. Dom Pedro I, nº 698",
    andar: "11º Andar",
    numeroAndar: 11,
    referencia: "11º andar (último andar de varas), corredor direito.",
    telefone: "(91) 4008-7164",
    ramal: "7164",
    email: "vt18belem.sec@trt8.jus.br",
    juizTitular: "Georgia Lima Pitman",
    diretor: "José Luiz Quaresma Lima",
    tags: ["18", "18a", "decima oitava", "décima oitava", "vara", "vt18"]
  },
  {
    id: "vt-19",
    nome: "19ª Vara do Trabalho de Belém",
    sigla: "19ª VT",
    categoria: "varas",
    predio: "Fórum Trabalhista (Ed. Alencastro)",
    endereco: "Tv. Dom Pedro I, nº 698",
    andar: "11º Andar",
    numeroAndar: 11,
    referencia: "11º andar, corredor esquerdo, em frente à 18ª Vara.",
    telefone: "(91) 4008-7019",
    ramal: "7019",
    email: "vt19belem.sec@trt8.jus.br",
    juizTitular: "Claudine Teixeira da Silva Rodrigues",
    diretor: "Marcelle Karine Gomes Cristino",
    tags: ["19", "19a", "decima nona", "décima nona", "vara", "vt19"]
  },

  // --- TECNOLOGIA DA INFORMAÇÃO, SUPORTE E HELP DESK (SETIN) ---
  {
    id: "setin-geral",
    nome: "SETIN - Secretaria de Tecnologia da Informação e Comunicações",
    sigla: "SETIN",
    categoria: "ti",
    predio: "Edifício-Sede",
    endereco: "Tv. Dom Pedro I, nº 746",
    andar: "2º Andar",
    numeroAndar: 2,
    referencia: "Edifício-Sede, 2º andar, entrada pela ala técnica de tecnologia.",
    telefone: "(91) 4008-7000",
    ramal: "7050",
    email: "setin@trt8.jus.br",
    juizTitular: "Secretário de TIC",
    diretor: "Equipe de Gestão de TIC",
    tags: ["setin", "ti", "informatica", "tecnologia", "secretaria ti", "sistemas"]
  },
  {
    id: "ti-suporte",
    nome: "Central de Atendimento ao Usuário (CAU) / Help Desk / Suporte Técnico",
    sigla: "CAU / Suporte TI",
    categoria: "ti",
    predio: "Edifício-Sede & Fórum",
    endereco: "Tv. Dom Pedro I, nº 746 (Base Sede) e Apoio Fórum nº 698",
    andar: "Térreo / 1º Andar",
    numeroAndar: 1,
    referencia: "Base de apoio dos técnicos e estagiários de informática onde os chamados são despachados.",
    telefone: "(91) 4008-7000",
    ramal: "7100 / 7120",
    email: "suporte@trt8.jus.br",
    juizTitular: "Coordenadoria de Suporte ao Usuário",
    diretor: "Supervisor de Atendimento",
    tags: ["suporte", "chamados", "cau", "helpdesk", "estagiarios", "cabos", "equipamento", "tecnico"]
  },
  {
    id: "ti-datacenter",
    nome: "Datacenter / Sala de Servidores do TRT-8",
    sigla: "Datacenter TRT8",
    categoria: "ti",
    predio: "Edifício-Sede",
    endereco: "Tv. Dom Pedro I, nº 746",
    andar: "Subsolo / Térreo Técnico",
    numeroAndar: 0,
    referencia: "Área de acesso restrito com identificação biométrica na Sede.",
    telefone: "(91) 4008-7000",
    ramal: "7080",
    email: "redes@trt8.jus.br",
    juizTitular: "Divisão de Infraestrutura e Redes",
    diretor: "Chefe do Datacenter",
    tags: ["datacenter", "servidores", "rack", "rede", "infraestrutura", "nobreak"]
  },

  // --- SEGUNDO GRAU: TURMAS, SESSÕES E TRIBUNAL PLENO ---
  {
    id: "turma-01",
    nome: "1ª Turma de Julgamento",
    sigla: "1ª Turma",
    categoria: "turmas",
    predio: "Edifício-Sede",
    endereco: "Tv. Dom Pedro I, nº 746",
    andar: "3º Andar",
    numeroAndar: 3,
    referencia: "Edifício-Sede, 3º andar, Secretaria da 1ª Turma.",
    telefone: "(91) 4008-7061",
    ramal: "7061",
    email: "turma1@trt8.jus.br",
    juizTitular: "Desembargador Presidente da Turma",
    diretor: "Secretário da 1ª Turma",
    tags: ["turma 1", "primeira turma", "sessao", "acordao", "2 grau"]
  },
  {
    id: "turma-02",
    nome: "2ª Turma de Julgamento",
    sigla: "2ª Turma",
    categoria: "turmas",
    predio: "Edifício-Sede",
    endereco: "Tv. Dom Pedro I, nº 746",
    andar: "3º Andar",
    numeroAndar: 3,
    referencia: "Edifício-Sede, 3º andar, ao lado da 1ª Turma.",
    telefone: "(91) 4008-7062",
    ramal: "7062",
    email: "turma2@trt8.jus.br",
    juizTitular: "Desembargador Presidente da Turma",
    diretor: "Secretário da 2ª Turma",
    tags: ["turma 2", "segunda turma", "sessao", "2 grau"]
  },
  {
    id: "turma-03",
    nome: "3ª Turma de Julgamento",
    sigla: "3ª Turma",
    categoria: "turmas",
    predio: "Edifício-Sede",
    endereco: "Tv. Dom Pedro I, nº 746",
    andar: "4º Andar",
    numeroAndar: 4,
    referencia: "Edifício-Sede, 4º andar.",
    telefone: "(91) 4008-7063",
    ramal: "7063",
    email: "turma3@trt8.jus.br",
    juizTitular: "Desembargador Presidente da Turma",
    diretor: "Secretário da 3ª Turma",
    tags: ["turma 3", "terceira turma", "sessao", "2 grau"]
  },
  {
    id: "turma-04",
    nome: "4ª Turma de Julgamento",
    sigla: "4ª Turma",
    categoria: "turmas",
    predio: "Edifício-Sede",
    endereco: "Tv. Dom Pedro I, nº 746",
    andar: "4º Andar",
    numeroAndar: 4,
    referencia: "Edifício-Sede, 4º andar, ala leste.",
    telefone: "(91) 4008-7064",
    ramal: "7064",
    email: "turma4@trt8.jus.br",
    juizTitular: "Desembargador Presidente da Turma",
    diretor: "Secretário da 4ª Turma",
    tags: ["turma 4", "quarta turma", "sessao", "2 grau"]
  },
  {
    id: "pleno-tribunal",
    nome: "Tribunal Pleno / Salão Nobre de Sessões",
    sigla: "Tribunal Pleno",
    categoria: "turmas",
    predio: "Edifício-Sede",
    endereco: "Tv. Dom Pedro I, nº 746",
    andar: "4º Andar",
    numeroAndar: 4,
    referencia: "Edifício-Sede, 4º andar, salão principal de julgamentos e posses.",
    telefone: "(91) 4008-7070",
    ramal: "7070",
    email: "pleno@trt8.jus.br",
    juizTitular: "Desembargador(a) Presidente do TRT-8",
    diretor: "Secretaria-Geral Judiciária",
    tags: ["pleno", "salao nobre", "tribunal pleno", "julgamento", "transmissao", "posse"]
  },

  // --- ALTA ADMINISTRAÇÃO E GABINETES ---
  {
    id: "presidencia",
    nome: "Presidência do TRT-8",
    sigla: "PRESI",
    categoria: "administracao",
    predio: "Edifício-Sede",
    endereco: "Tv. Dom Pedro I, nº 746",
    andar: "5º Andar",
    numeroAndar: 5,
    referencia: "Edifício-Sede, 5º andar, recepção da Presidência.",
    telefone: "(91) 4008-7001",
    ramal: "7001",
    email: "presidencia@trt8.jus.br",
    juizTitular: "Desembargador(a) Presidente",
    diretor: "Secretário-Geral da Presidência",
    tags: ["presidencia", "presidente", "presi", "gabinete da presidencia", "diretoria"]
  },
  {
    id: "vice-presidencia",
    nome: "Vice-Presidência do TRT-8",
    sigla: "VICE-PRESI",
    categoria: "administracao",
    predio: "Edifício-Sede",
    endereco: "Tv. Dom Pedro I, nº 746",
    andar: "5º Andar",
    numeroAndar: 5,
    referencia: "Edifício-Sede, 5º andar, ala sul.",
    telefone: "(91) 4008-7002",
    ramal: "7002",
    email: "vice-presidencia@trt8.jus.br",
    juizTitular: "Desembargador(a) Vice-Presidente",
    diretor: "Chefia de Gabinete",
    tags: ["vice", "vice-presidencia", "precatorios", "nugepnac"]
  },
  {
    id: "corregedoria",
    nome: "Corregedoria Regional do TRT-8",
    sigla: "CORREG",
    categoria: "administracao",
    predio: "Edifício-Sede",
    endereco: "Tv. Dom Pedro I, nº 746",
    andar: "5º Andar",
    numeroAndar: 5,
    referencia: "Edifício-Sede, 5º andar, ala norte.",
    telefone: "(91) 4008-7003",
    ramal: "7003",
    email: "corregedoria@trt8.jus.br",
    juizTitular: "Desembargador(a) Corregedor(a)",
    diretor: "Secretário da Corregedoria",
    tags: ["corregedoria", "corregedor", "inspecao", "correicao"]
  },
  {
    id: "gabinetes-desembargadores",
    nome: "Gabinetes dos Desembargadores (GABs)",
    sigla: "Gabinetes Des.",
    categoria: "administracao",
    predio: "Edifício-Sede",
    endereco: "Tv. Dom Pedro I, nº 746",
    andar: "3º, 4º e 5º Andares",
    numeroAndar: 3,
    referencia: "Distribuídos nos andares superiores do Edifício-Sede ao redor dos átrios centrais.",
    telefone: "(91) 4008-7000",
    ramal: "7000 (Central de Ramais)",
    email: "gabinetes@trt8.jus.br",
    juizTitular: "Desembargadores do Trabalho",
    diretor: "Assessores de Gabinete",
    tags: ["gabinete", "desembargador", "assessor", "desembargadora", "segundo grau"]
  },

  // --- SETORES DE APOIO, ATENDIMENTO AO PÚBLICO E ÁREAS COMUNS ---
  {
    id: "protocolo-geral",
    nome: "Protocolo Geral do Tribunal",
    sigla: "Protocolo",
    categoria: "comum",
    predio: "Fórum Trabalhista (Ed. Alencastro)",
    endereco: "Tv. Dom Pedro I, nº 698",
    andar: "Térreo",
    numeroAndar: 1,
    referencia: "Térreo do Fórum Trabalhista, logo após a entrada pela Tv. Dom Pedro I.",
    telefone: "(91) 4008-7100",
    ramal: "7100",
    email: "protocolo@trt8.jus.br",
    juizTitular: "Distribuição e Protocolo",
    diretor: "Chefe do Protocolo",
    tags: ["protocolo", "peticao", "entrada", "documentos", "terreo"]
  },
  {
    id: "ouvidoria-sic",
    nome: "Ouvidoria Regional e SIC (Serviço de Informação ao Cidadão)",
    sigla: "Ouvidoria / SIC",
    categoria: "comum",
    predio: "Edifício-Sede",
    endereco: "Tv. Dom Pedro I, nº 746",
    andar: "Térreo / Hall Principal",
    numeroAndar: 1,
    referencia: "Hall de entrada do Edifício-Sede, ao lado da recepção geral.",
    telefone: "(91) 4008-7250",
    ramal: "7250",
    email: "ouvidoria@trt8.jus.br",
    juizTitular: "Ouvidor Regional",
    diretor: "Coordenador da Ouvidoria",
    tags: ["ouvidoria", "sic", "informacao", "cidadao", "atendimento", "hall", "terreo"]
  },
  {
    id: "cejusc-belem",
    nome: "CEJUSC Belém (Centro Judiciário de Conciliação)",
    sigla: "CEJUSC",
    categoria: "comum",
    predio: "Fórum Trabalhista (Ed. Alencastro)",
    endereco: "Tv. Dom Pedro I, nº 698",
    andar: "1º Andar",
    numeroAndar: 1,
    referencia: "1º andar do Fórum Trabalhista, salas de audiência de conciliação e mediação.",
    telefone: "(91) 4008-7200",
    ramal: "7200",
    email: "cejusc.belem@trt8.jus.br",
    juizTitular: "Juiz Coordenador do CEJUSC",
    diretor: "Secretário do CEJUSC",
    tags: ["cejusc", "conciliacao", "acordo", "mediacao", "audiencia"]
  },
  {
    id: "central-mandados",
    nome: "Central de Mandados (Oficiais de Justiça)",
    sigla: "Central de Mandados",
    categoria: "comum",
    predio: "Fórum Trabalhista (Ed. Alencastro)",
    endereco: "Tv. Dom Pedro I, nº 698",
    andar: "2º Andar",
    numeroAndar: 2,
    referencia: "2º andar do Fórum Trabalhista, ala dos Oficiais de Justiça Avaliadores.",
    telefone: "(91) 4008-7180",
    ramal: "7180",
    email: "mandados.belem@trt8.jus.br",
    juizTitular: "Juiz Diretor do Foro",
    diretor: "Chefe da Central de Mandados",
    tags: ["mandados", "oficial de justica", "oficiais", "cumprimento", "notificacao"]
  },
  {
    id: "sala-oab",
    nome: "Sala de Apoio à Advocacia (OAB / Sala dos Advogados)",
    sigla: "Sala da OAB",
    categoria: "comum",
    predio: "Fórum Trabalhista (Ed. Alencastro)",
    endereco: "Tv. Dom Pedro I, nº 698",
    andar: "Térreo",
    numeroAndar: 1,
    referencia: "Térreo do Fórum, próxima aos elevadores de acesso público.",
    telefone: "(91) 4008-7105",
    ramal: "7105",
    email: "oab.trt8@oabpa.org.br",
    juizTitular: "Representação OAB/PA",
    diretor: "Atendente OAB",
    tags: ["oab", "advogado", "advocacia", "consulta", "pje", "sala oab"]
  },
  {
    id: "auditorio-aloysio",
    nome: "Auditório Aloysio da Costa Chaves",
    sigla: "Auditório Principal",
    categoria: "comum",
    predio: "Edifício-Sede",
    endereco: "Tv. Dom Pedro I, nº 746",
    andar: "Térreo / 1º Andar",
    numeroAndar: 1,
    referencia: "Acesso pelo saguão principal do Edifício-Sede.",
    telefone: "(91) 4008-7040",
    ramal: "7040",
    email: "eventos@trt8.jus.br",
    juizTitular: "Comissão de Eventos",
    diretor: "Cerimonial do TRT-8",
    tags: ["auditorio", "eventos", "aloysio", "palestra", "seminario", "cerimonial"]
  },
  {
    id: "biblioteca",
    nome: "Biblioteca Francisco Aloysio Cavalcante",
    sigla: "Biblioteca TRT8",
    categoria: "comum",
    predio: "Edifício-Sede",
    endereco: "Tv. Dom Pedro I, nº 746",
    andar: "2º Andar",
    numeroAndar: 2,
    referencia: "Edifício-Sede, 2º andar, ala oeste.",
    telefone: "(91) 4008-7090",
    ramal: "7090",
    email: "biblioteca@trt8.jus.br",
    juizTitular: "Comissão de Documentação",
    diretor: "Bibliotecário-Chefe",
    tags: ["biblioteca", "livros", "estudo", "pesquisa", "doutrina"]
  },
  {
    id: "escola-judicial",
    nome: "EJUD8 - Escola Judicial da 8ª Região",
    sigla: "EJUD8",
    categoria: "comum",
    predio: "Edifício-Sede",
    endereco: "Tv. Dom Pedro I, nº 746",
    andar: "2º Andar",
    numeroAndar: 2,
    referencia: "Edifício-Sede, 2º andar, próximo ao laboratório de informática de treinamentos.",
    telefone: "(91) 4008-7240",
    ramal: "7240",
    email: "ejud8@trt8.jus.br",
    juizTitular: "Desembargador Diretor da EJUD",
    diretor: "Coordenador Pedagógico",
    tags: ["ejud", "escola judicial", "treinamento", "capacitacao", "curso"]
  },
  {
    id: "saude-medico",
    nome: "Coordenadoria de Saúde / Posto Médico e Odontológico",
    sigla: "Posto de Saúde",
    categoria: "comum",
    predio: "Edifício-Sede",
    endereco: "Tv. Dom Pedro I, nº 746",
    andar: "1º Andar",
    numeroAndar: 1,
    referencia: "Edifício-Sede, 1º andar, ala de atendimento médico e perícia oficial.",
    telefone: "(91) 4008-7230",
    ramal: "7230",
    email: "saude@trt8.jus.br",
    juizTitular: "Junta Médica Oficial",
    diretor: "Diretoria Médica",
    tags: ["saude", "medico", "enfermaria", "dentista", "odontologia", "pericia"]
  },
  {
    id: "copa-restaurante",
    nome: "Copa / Restaurante e Convivência",
    sigla: "Copa / Refeitório",
    categoria: "comum",
    predio: "Edifício-Sede & Fórum",
    endereco: "Tv. Dom Pedro I (Área de Convivência)",
    andar: "Térreo / Mezanino",
    numeroAndar: 1,
    referencia: "Área de apoio para servidores e estagiários tomarem café e almoçarem.",
    telefone: "(91) 4008-7000",
    ramal: "7000",
    email: "apoio@trt8.jus.br",
    juizTitular: "Administração Predial",
    diretor: "Supervisão Predial",
    tags: ["copa", "cafe", "almoco", "restaurante", "refeitorio", "lanche"]
  }
];

// Carrega dados salvos ou iniciais
function carregarLocaisCompletos() {
  const locaisSalvos = localStorage.getItem("trt8_locais_db");
  if (locaisSalvos) {
    try {
      const parsed = JSON.parse(locaisSalvos);
      if (Array.isArray(parsed) && parsed.length > 0) {
        return parsed;
      }
    } catch (e) {
      console.warn("Erro ao ler dados do localStorage, usando iniciais:", e);
    }
  }
  return DADOS_LOCAIS_INICIAIS;
}

// Salva dados no localStorage
function salvarLocaisNoStorage(lista) {
  localStorage.setItem("trt8_locais_db", JSON.stringify(lista));
}
